name = "Nalsai"
license = "MIT"
licenselink = "https://git.nalsai.de/nalsai.de/blob/main/LICENSE"
description = "My personal theme for my personal website."
homepage = "https://nalsai.de/"
tags = ["personal", "blog"]
features = []
min_version = "0.90.0"

[author]
  name = "Nalsai"
  homepage = "https://nalsai.de/"
