baseURL = "https://nalsai.de/"
title = "Nils' Website"
theme = "nalsai"
enableGitInfo = true

DefaultContentLanguage = "en"

[languages]
  	[languages.en]
    	baseURL = "https://en.nalsai.de"
		languageName = "English"
    	contentDir = "content/en"
		title = "Nils' Website"
		weight = 2
	[languages.de]
    	baseURL = "https://dev.nalsai.de"
		languageName = "Deutsch"
    	contentDir = "content/de"
		title = "Nils' Webseite"
		weight = 1

[privacy]
	[privacy.disqus]
		disable = true
	[privacy.googleAnalytics]
		disable = true
	[privacy.instagram]
		disable = true
	[privacy.twitter]
		disable = true
	[privacy.vimeo]
	    disable = true
	[privacy.youtube]
	    disable = true