[context.production.environment]
    HUGO_VERSION = "0.78.1"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.78.1"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.78.1"